datamodule:
  data_root: /Users/adamchlopowiec/Desktop/studia/magisterskie/semestr2/pdp/equivariant-map-gen/equivariantgan/storage/data
  target_size: 256
  num_workers: 8
  batch_size: 8

lightning_model:
  gan_type: e2_pix2pix
  generator:
    N: 4
    in_channels: 1
    out_channels: 1
    image_size: 256
    restriction: 3
    deltaorthonormal: False
    channel_div: 2
    to_trivial: True
    r1_subgroup: 2
    r2_subgroup: 4

  discriminator:
    N: 4
    in_channels: 2
    out_channels: 1
    image_size: 256
    restriction: 3
    deltaorthonormal: False
    channel_div: 2
    to_trivial: True
    r1_subgroup: 2
    r2_subgroup: 4

  loss_gan_mode: lsgan
  lambda_l1: 100.0
  AtoB: True
  lr_g: 0.0002
  lr_d: 0.0002

logger:
  project: map_gan
  entity: adamchlopowiec
  log_model: True
  mode: online
  save_dir: /Users/adamchlopowiec/Desktop/studia/magisterskie/semestr2/pdp/equivariant-map-gen/equivariantgan/storage/data

callbacks:
  model_checkpoint:
    verbose: True
    every_n_epochs: 5

training:
  trainer:
    accelerator: cpu
    devices: 1
    min_epochs: 1
    max_epochs: 500
    precision: 32
    strategy: auto
    inference_mode: True
    deterministic: warn