datamodule:
  data_root: /home/adrian/pdp/equivariant-map-gen/equivariantgan/storage_18/data
  target_size: 256
  num_workers: 8
  batch_size: 8
  rotate: True

lightning_model:
  gan_type: pix2pix
  generator:
    in_channels: 3
    out_channels: 3
    image_size: 256

  discriminator:
    in_channels: 6
    out_channels: 1
    image_size: 256

  loss_gan_mode: lsgan
  lambda_l1: 100.0
  AtoB: False
  lr_g: 0.0002
  lr_d: 0.0002

logger:
  project: map_gan
  entity: adamchlopowiec
  log_model: True
  mode: online
  save_dir: /home/adrian/pdp/equivariant-map-gen/equivariantgan/storage_18/data

callbacks:
  model_checkpoint:
    verbose: True
    every_n_epochs: 5

training:
  trainer:
    accelerator: gpu
    devices: [0]
    min_epochs: 1
    max_epochs: 500
    precision: 16-mixed
    strategy: auto
    inference_mode: True
    deterministic: warn
